# Generated by Django 4.2.1 on 2023-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Islaidu aprasymas')),
                ('repairs_cost', models.FloatField(verbose_name='Islaidu suma')),
                ('date', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Islaidos',
                'verbose_name_plural': 'Islaidos',
            },
        ),
        migrations.CreateModel(
            name='Kaupiamasis_Inasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_rate', models.FloatField(verbose_name='Mokėjimo koeficientas')),
            ],
            options={
                'verbose_name': 'Kaupiamasis Inasas',
                'verbose_name_plural': 'Kaupiamieji Inasai',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duties', models.CharField(max_length=255)),
                ('wage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Darbuotojas',
                'verbose_name_plural': 'Darbuotojai',
            },
        ),
    ]
