# Generated by Django 4.2.1 on 2023-08-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyventojas', '0001_initial'),
        ('administracija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaupiamasis_inasas',
            name='flat_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaupiamasis_inasas', to='gyventojas.flat'),
        ),
    ]
