# Generated by Django 4.2.1 on 2023-08-28 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diskusija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentaras',
            name='gyventojas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balsavimas',
            name='diskusija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diskusija.diskusija'),
        ),
        migrations.AddField(
            model_name='balsavimas',
            name='vartotojas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='balsavimas',
            unique_together={('vartotojas', 'diskusija')},
        ),
    ]
